tw-rs: mark broken
probably outdated dependencies
updating to latest release 0.1.29 or even 0.1.34
does not compile because of:
error[E0554]: #![feature] may not be used on the stable release channel